### ISSUE TITLE
 Running heat_map.py: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by melaanya** [philipperemy/keract#37] opened 2019-04-30 16:02 UTC
Hello @philipperemy!
I'm currently facing the following issue: when running heat_map.py I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/misha/Desktop/dev-anna/15sof/shot_detection/src/scripts/heat_map.py", line 31, in <module>
    activations = keract.get_activations(model, image)
  File "/home/misha/anaconda3/envs/conda-py3/lib/python3.6/site-packages/keract/keract.py", line 77, in get_activations
    activations = _evaluate(model, layer_outputs, x, y=None)
  File "/home/misha/anaconda3/envs/conda-py3/lib/python3.6/site-packages/keract/keract.py", line 23, in _evaluate
    x_, y_, sample_weight_ = model._standardize_user_data(x, y)
  File "/home/misha/anaconda3/envs/conda-py3/lib/python3.6/site-packages/keras/engine/training.py", line 1487, in _standardize_user_data
    in zip(y, sample_weights, class_weights, self._feed_sample_weight_modes)]
  File "/home/misha/anaconda3/envs/conda-py3/lib/python3.6/site-packages/keras/engine/training.py", line 1486, in <listcomp>
    for (ref, sw, cw, mode)
  File "/home/misha/anaconda3/envs/conda-py3/lib/python3.6/site-packages/keras/engine/training.py", line 540, in _standardize_weights
    return np.ones((y.shape[0],), dtype=K.floatx())
AttributeError: 'NoneType' object has no attribute 'shape'
```

Library versions are as follows:
```
keract==2.5.4
Keras==2.1.6
tensorflow-gpu==1.9.0
```

Could you please advise what might be the problem?

**Comment by qwertpi** [comment] 2019-04-30 16:05
I wrote the keract.display_heatmaps code that is ran in [this heat_map.py](https://github.com/philipperemy/keract/blob/master/examples/heat_map.py), is this the one you are running?

**Comment by melaanya** [comment] 2019-04-30 20:33
Yes, I run exactly the same heat_map.py from the repo.

**Comment by qwertpi** [comment] 2019-05-01 06:59
That's odd, @philipperemy wrote that code so it would be helpful to get some input from them but the error seems to suggest to me that the image that is being passed to get_activations contains no data

**Comment by qwertpi** [comment] 2019-05-01 07:06
Going out on a limb here but I noticed your location in your GitHub bio is in Russia and the heat_map.py retrieves the image it uses from Wikipedia. Is there any chance that the download could be getting blocked? What happens if you navigate to [https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Gatto_europeo4.jpg/250px-Gatto_europeo4.jpg](https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Gatto_europeo4.jpg/250px-Gatto_europeo4.jpg) in a browser?

**Comment by melaanya** [comment] 2019-05-01 16:12
Yes, it has been retrieved fine, and it is predicted correctly: the output is 
`Egyptian_cat (47.48033285140991)`

**Comment by qwertpi** [comment] 2019-05-01 21:14
That’s doubly odd. Are you sure you have an unaltered latest version of the
code? Could you maybe put the code you are running in a GitHub gist and put
a link to the gist in this thread?

**Comment by melaanya** [comment] 2019-05-01 21:35
Sure, here it is [heat_map.py](https://gist.github.com/melaanya/5fe45bc2fd3c7144ca03dee1bb06040c).

**Comment by philipperemy** [comment] 2019-05-10 07:08
@melaanya I could run your example from a fresh install and it worked like a charm. Are you using a headless server? I am running on MacOS.

**Comment by philipperemy** [comment] 2019-05-14 04:20
I'll close this issue because I am unable to reproduce it.

**Comment by philipperemy** [comment] 2019-05-14 04:20
I'll close this issue because I am unable to reproduce it.

**Closed by philipperemy** 2019-05-14 04:20 UTC
