### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'flat'

### ISSUE THREAD

**Issue by venergiac** [philipperemy/keract#105] opened 2020-07-02 06:49 UTC
I applied keract to my VQ-VAE

on

`kt.display_heatmaps(activations, img_o, save=False)`

I got

`AttributeError: 'AxesSubplot' object has no attribute 'flat'`

but 
`kt.display_actovations(activations, save=False)`

worked well.

I used VGG16 and keract worked well for both cases.

I solved changing the keract 

`def display_heatmaps(activations, input_image, directory='.', save=False, fix=True):`

          if hasattr(axes,'flat'):
                    axes.flat[i].imshow(input_image / 255.0)

                    axes.flat[i].imshow(img, alpha=0.3, cmap='jet', interpolation='bilinear')
                else:
                    axes.imshow(input_image / 255.0)
                    axes.imshow(img, alpha=0.3, cmap='jet', interpolation='bilinear')
            if hasattr(axes,'flat'):
                axes.flat[i].axis('off')
            else:
                axes.axis('off')

but it is a workaround

**Comment by philipperemy** [comment] 2020-07-04 03:31
@venergiac thanks for reporting. I'm going to see if there's a better way to handle this.

**Comment by philipperemy** [comment] 2020-07-04 03:39
Do you have a snippet that reproduces the problem? I can't reproduce it on a toy example. Thanks!

**Comment by philipperemy** [comment] 2020-07-06 18:30
I could reproduce the error. I guess this workaround works just fine for now. I'll push that to the codebase and will update it later when I have more time to understand exactly what's going on.

**Comment by philipperemy** [comment] 2020-07-06 18:42
Fixed in https://github.com/philipperemy/keract/commit/48ebbc7ac13e1a104eafe3ce7fd799d361664a1e

**Closed by philipperemy** 2020-07-06 18:42 UTC

**Comment by philipperemy** [comment] 2020-07-06 18:44
Released in 4.2.2

**Comment by venergiac** [comment] 2020-07-07 06:14
yes confirmed now it works
