### ISSUE TITLE
Error in get_activations function

### ISSUE THREAD

**Issue by CCH0124** [philipperemy/keract#121] opened 2020-09-29 09:16 UTC
My network
```python
dos_input = Input(shape=(1, 77))
forward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4) , recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True)
backward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4) , recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True , go_backwards=True)
bi_one = Bidirectional(forward_layer_one, backward_layer=backward_layer_one, name='bi_one')(dos_input)

noise_one = GaussianNoise(0.5)(bi_one)

bn_one = BatchNormalization()(noise_one)

forward_layer_two = LSTM(32, return_sequences=True)
backward_layer_two = LSTM(32, return_sequences=True, go_backwards=True)
bi_two = Bidirectional(forward_layer_two, backward_layer=backward_layer_two, name='bi_two')(bn_one)

bn_two = BatchNormalization()(bi_two)

forward_layer_three = LSTM(16,)
backward_layer_three = LSTM(16, go_backwards=True)
bi_three = Bidirectional(forward_layer_three, backward_layer=backward_layer_three, name='bi_three')(bn_two)

bn_three = BatchNormalization()(bi_three)

flatten_one = Flatten()(bn_three)

dense_four = Dense(16, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4), name='dense_three')(flatten_one)
noise_two = GaussianNoise(0.5)(dense_four)
avtivation_four = Activation(tf.nn.relu6, name='dense_four_activation')(noise_two)

bn_four = BatchNormalization()(avtivation_four)

dense = Dense(2, name='classification')(bn_four)
output_res = Activation(tf.nn.softmax, name='classifi')(dense)

model = Model(inputs=dos_input, outputs=output_res)

algorithm = tf.keras.optimizers.SGD(learning_rate=0.05, momentum=0.99, clipvalue=0.2, nesterov=True, name='SGD')

model.compile(optimizer=algorithm, loss='binary_crossentropy', metrics=modelmetric.metric('binary_crossentropy'))
```

env：
- keras  2.3.0-tf
- tensorflow 2.2.0
- keract 4.3.2

I want to get information about the classification layer. However, the following error occurred.

Error message：
```
InternalError:  [_Derived_]  Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 77, 64, 1, 1, 691406, 64] 
	 [[{{node CudnnRNN}}]]
	 [[bi_one/forward_lstm/StatefulPartitionedCall]] [Op:__inference_keras_scratch_graph_29222]

Function call stack:
keras_scratch_graph -> keras_scratch_graph -> keras_scratch_graph
```

**Comment by philipperemy** [comment] 2020-09-29 11:13
Thank you for reporting. It seems to be a bug indeed. Will work on a fix asap.

**Comment by philipperemy** [comment] 2020-09-29 12:34
I'm using this code and it seems to work:

- tensorflow 2.3.0
- keract 4.3.2

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import LSTM, Bidirectional, GaussianNoise, BatchNormalization, Dense, Flatten, \
    Activation

import keract

dos_input = Input(shape=(1, 77))
forward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4),
                         recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True)
backward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4),
                          recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True,
                          go_backwards=True)
bi_one = Bidirectional(forward_layer_one, backward_layer=backward_layer_one, name='bi_one')(dos_input)

noise_one = GaussianNoise(0.5)(bi_one)

bn_one = BatchNormalization()(noise_one)

forward_layer_two = LSTM(32, return_sequences=True)
backward_layer_two = LSTM(32, return_sequences=True, go_backwards=True)
bi_two = Bidirectional(forward_layer_two, backward_layer=backward_layer_two, name='bi_two')(bn_one)

bn_two = BatchNormalization()(bi_two)

forward_layer_three = LSTM(16, )
backward_layer_three = LSTM(16, go_backwards=True)
bi_three = Bidirectional(forward_layer_three, backward_layer=backward_layer_three, name='bi_three')(bn_two)

bn_three = BatchNormalization()(bi_three)

flatten_one = Flatten()(bn_three)

dense_four = Dense(16, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4), name='dense_three')(flatten_one)
noise_two = GaussianNoise(0.5)(dense_four)
avtivation_four = Activation(tf.nn.relu6, name='dense_four_activation')(noise_two)

bn_four = BatchNormalization()(avtivation_four)

dense = Dense(2, name='classification')(bn_four)
output_res = Activation(tf.nn.softmax, name='classifi')(dense)

model = Model(inputs=dos_input, outputs=output_res)

algorithm = tf.keras.optimizers.SGD(learning_rate=0.05, momentum=0.99, clipvalue=0.2, nesterov=True, name='SGD')

model.compile(optimizer=algorithm, loss='binary_crossentropy')

model.summary()

x = np.ones(shape=(1, 1, 77))
print(keract.get_activations(model, x, layer_names='classification'))
print(model.predict_on_batch(x))
```

I get

```
{'classification': array([[-0.01190728,  0.01834971]], dtype=float32)}
[[0.49243632 0.50756365]]
```

So a couple of possibilities:
- Either I'm not testing the right thing.
- Either you are not importing the right classes for tensorflow.
- Either tensorflow 2.2 does not work and 2.3 will work.

Try to uninstall keras you don't need to use Keras anymore (it's bundled with tensorflow).

**Comment by CCH0124** [comment] 2020-09-29 13:41
This method is available.
However, when I save the network as a model, and then I import the model and call `get_activations` when predicting, the above error is issued.

**Comment by philipperemy** [comment] 2020-09-29 13:54
Can you paste a snippet that I can run to reproduce this error? A full (but minimal) code. Thanks!

**Comment by CCH0124** [comment] 2020-09-29 23:24
```python
dos_input = Input(shape=(1, 77))
forward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4) , recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True)
backward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4) , recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True , go_backwards=True)
bi_one = Bidirectional(forward_layer_one, backward_layer=backward_layer_one, name='bi_one')(dos_input)

noise_one = GaussianNoise(0.5)(bi_one)

bn_one = BatchNormalization()(noise_one)

forward_layer_two = LSTM(32, return_sequences=True)
backward_layer_two = LSTM(32, return_sequences=True, go_backwards=True)
bi_two = Bidirectional(forward_layer_two, backward_layer=backward_layer_two, name='bi_two')(bn_one)

bn_two = BatchNormalization()(bi_two)

forward_layer_three = LSTM(16,)
backward_layer_three = LSTM(16, go_backwards=True)
bi_three = Bidirectional(forward_layer_three, backward_layer=backward_layer_three, name='bi_three')(bn_two)

bn_three = BatchNormalization()(bi_three)

flatten_one = Flatten()(bn_three)

dense_four = Dense(16, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4), name='dense_three')(flatten_one)
noise_two = GaussianNoise(0.5)(dense_four)
avtivation_four = Activation(tf.nn.relu6, name='dense_four_activation')(noise_two)

bn_four = BatchNormalization()(avtivation_four)

dense = Dense(2, name='classification')(bn_four)
output_res = Activation(tf.nn.softmax, name='classifi')(dense)

model = Model(inputs=dos_input, outputs=output_res)

algorithm = tf.keras.optimizers.SGD(learning_rate=0.05, momentum=0.99, clipvalue=0.2, nesterov=True, name='SGD')

model.compile(optimizer=algorithm, loss='binary_crossentropy', metrics=modelmetric.metric('binary_crossentropy'))
```

After the above network is trained, save the model.

```python
model.save('../model_record/'+dir_name+'/model/model.h5')
```

Then another file is imports into the model to make predictions and call `get_activations`.

```python
model = tf.keras.models.load_model(model_path, custom_objects={'relu6': tf.nn.relu6})
y_pred = model.predict(X)
import keract
v_sigmoid = keract.get_activations(model,X, layer_names='classification')
```

**Comment by philipperemy** [comment] 2020-09-30 00:28
This works very well for me:

file1.py
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import LSTM, Bidirectional, GaussianNoise, BatchNormalization, Dense, Flatten, \
    Activation

import keract

dos_input = Input(shape=(1, 77))
forward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4),
                         recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True)
backward_layer_one = LSTM(64, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4),
                          recurrent_constraint=tf.keras.constraints.MaxNorm(max_value=4), return_sequences=True,
                          go_backwards=True)
bi_one = Bidirectional(forward_layer_one, backward_layer=backward_layer_one, name='bi_one')(dos_input)

noise_one = GaussianNoise(0.5)(bi_one)

bn_one = BatchNormalization()(noise_one)

forward_layer_two = LSTM(32, return_sequences=True)
backward_layer_two = LSTM(32, return_sequences=True, go_backwards=True)
bi_two = Bidirectional(forward_layer_two, backward_layer=backward_layer_two, name='bi_two')(bn_one)

bn_two = BatchNormalization()(bi_two)

forward_layer_three = LSTM(16, )
backward_layer_three = LSTM(16, go_backwards=True)
bi_three = Bidirectional(forward_layer_three, backward_layer=backward_layer_three, name='bi_three')(bn_two)

bn_three = BatchNormalization()(bi_three)

flatten_one = Flatten()(bn_three)

dense_four = Dense(16, kernel_constraint=tf.keras.constraints.MaxNorm(max_value=4), name='dense_three')(flatten_one)
noise_two = GaussianNoise(0.5)(dense_four)
avtivation_four = Activation(tf.nn.relu6, name='dense_four_activation')(noise_two)

bn_four = BatchNormalization()(avtivation_four)

dense = Dense(2, name='classification')(bn_four)
output_res = Activation(tf.nn.softmax, name='classifi')(dense)

model = Model(inputs=dos_input, outputs=output_res)

algorithm = tf.keras.optimizers.SGD(learning_rate=0.05, momentum=0.99, clipvalue=0.2, nesterov=True, name='SGD')

model.compile(optimizer=algorithm, loss='binary_crossentropy')

model.summary()

x = np.ones(shape=(1, 1, 77))
print(keract.get_activations(model, x, layer_names='classification'))
print(model.predict_on_batch(x))

model.save('model.h5')
```

file2.py
```python
import numpy as np
import tensorflow as tf

x = np.ones(shape=(1, 1, 77))

model2 = tf.keras.models.load_model('model.h5', custom_objects={'relu6': tf.nn.relu6})
y_pred = model2.predict(x)
import keract

v_sigmoid = keract.get_activations(model2, x, layer_names='classification')
print(v_sigmoid)
```

Output of file2.py
```
2020-09-30 09:27:50.302157: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-30 09:27:50.312708: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd5c9ee76a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-30 09:27:50.312720: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
{'classification': array([[-0.00790902,  0.00817255]], dtype=float32)}
```

Try to upgrade tensorflow to 2.3.0. It may be the problem. And double check your imports.

**Comment by philipperemy** [comment] 2020-09-30 00:29
Also worth mentioning. I get the same values with `keract` before and after saving the model.

**Comment by CCH0124** [comment] 2020-09-30 03:32
Sorry, I forgot to mention that I use the GPU environment.
But I will try the CPU.

**Comment by philipperemy** [comment] 2020-09-30 05:08
There might be a tensorflow bug if you define your model and save it on CPU and transfer it to a GPU machine. I know it's not that trivial to do in Pytorch. Let me know.

**Comment by CCH0124** [comment] 2020-10-01 12:25
I temporarily use the CPU mode to work.

**Comment by philipperemy** [comment] 2020-10-05 01:49
Ok thank you. I'll close this issue for now.

**Closed by philipperemy** 2020-10-05 01:49 UTC
Labels: question
